name: "Build"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ci_db_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2.3.4
      - name: "Basic" 
        working-directory: 'src/basics'
        run: |
            cargo run
      - name: "Maps" 
        working-directory: 'src/maps'
        run: |
            cargo run
      - name: "Databases" 
        working-directory: 'src/dbproject'
        run: |
            export DATABASE_URL=postgres://postgres:postgres@postgres/ci_db_test
            cargo install diesel_cli --no-default-features --features postgres
            diesel setup
            cargo run --bin show_posts 
