name: "Build"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres_db
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres_user
          POSTGRES_PASSWORD: postgres_password
        ports:
          - 5432:5432
        options: 
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2.3.4
      - name: "Basic" 
        working-directory: 'src/basics'
        run: |
            cargo run
      - name: "Maps" 
        working-directory: 'src/maps'
        run: |
            cargo run
      - name: "Installing diesel_cli" 
        working-directory: 'src/dbproject'
        run: |
            cargo install diesel_cli --no-default-features --features postgres
      - name: "Databases" 
        working-directory: 'src/dbproject'
        env:
          DATABASE_URL: postgres://postgres_user:postgres_password@localhost:5432/postgres_db
        run: |
            diesel setup
            cargo run --bin new_published_post 'sample' 'abc' 
            cargo run --bin show_posts 
