name: "Build"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: "Basic" 
        working-directory: 'src/basics'
        run: |
            cargo run
      - name: "Maps" 
        working-directory: 'src/maps'
        run: |
            cargo run
